stages:
  - test
  - build
  - publish

functional tests:
  stage: test
  # had to pick one.
  image: debian:buster
  script:
    - apt-get update -qq
    - apt-get install -y git-core pandoc ruby ruby-dev rubygems build-essential dpkg-dev sbcl curl zlib1g-dev
    - ./.ci/build.sh
    # Has to be last.
    - (cd tests/functional; ./run-tests)

.compile-debian: &compile-debian
  stage: build
  image: debian:${DIST}
  script:
    - apt-get update -qq
    # git-core: needed to run git clone a bit later
    # pandoc: needed to build the manual
    # ruby/ruby-dev/rubygems/build-essential: needed to install fpm
    # dpkg-dev: needed to build a .deb
    # zlib1g-dev: sbcl dependency
    - apt-get install -y git-core pandoc ruby ruby-dev rubygems build-essential dpkg-dev sbcl curl zlib1g-dev
    - ./.ci/build.sh
    - make deb VERSION="${CI_BUILD_TAG:-1.0.0}"
    - mv ballish_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish_"${DIST}"_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb
  artifacts:
    expire_in: '1 hour'
    paths:
      - ballish_${DIST}_${CI_BUILD_TAG:-1.0.0}_amd64.deb

.compile-ubuntu: &compile-ubuntu
  stage: build
  image: ubuntu:${DIST}
  script:
    - apt-get update -qq
    # git-core: needed to run git clone a bit later
    # pandoc: needed to build the manual
    # ruby/ruby-dev/rubygems/build-essential: needed to install fpm
    # dpkg-dev: needed to build a .deb
    # zlib1g-dev: sbcl dependency
    - apt-get install -y git-core pandoc ruby ruby-dev rubygems build-essential dpkg-dev sbcl curl zlib1g-dev
    - ./.ci/build.sh
    - make deb VERSION="${CI_BUILD_TAG:-1.0.0}"
    - mv ballish_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish_ubuntu_"${DIST}"_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb
  artifacts:
    expire_in: '1 hour'
    paths:
      - ballish_ubuntu_${DIST}_${CI_BUILD_TAG:-1.0.0}_amd64.deb

.compile-fedora: &compile-fedora
  stage: build
  image: fedora:${DIST}
  script:
    - dnf groupinstall -y "Development Tools"
    - dnf install -y git pandoc ruby ruby-devel rubygems rpm-build sbcl curl zlib-devel libffi-devel redhat-rpm-config
    - ./.ci/build.sh
    - make rpm VERSION="${CI_BUILD_TAG:-1.0.0}"
    - mv ballish-"${CI_BUILD_TAG:-1.0.0}"-1.x86_64.rpm ballish-"${CI_BUILD_TAG:-1.0.0}"-1.f${DIST}.x86_64.rpm
  artifacts:
    expire_in: '1 hour'
    paths:
      - ballish-${CI_BUILD_TAG:-1.0.0}-1.f${DIST}.x86_64.rpm

compile-debian-stretch:
  variables:
    DIST: stretch
  <<: *compile-debian

compile-debian-buster:
  variables:
    DIST: buster
  <<: *compile-debian

compile-debian-bullseye:
  variables:
    DIST: bullseye
  <<: *compile-debian

compile-ubuntu-18.04:
  variables:
    DIST: "18.04"
  <<: *compile-ubuntu

compile-ubuntu-19.10:
  variables:
    DIST: "19.10"
  <<: *compile-ubuntu

compile-ubuntu-20.04:
  variables:
    DIST: "20.04"
  <<: *compile-ubuntu

compile-fedora-31:
  variables:
    DIST: "31"
  <<: *compile-fedora

compile-fedora-32:
  variables:
    DIST: "32"
  <<: *compile-fedora

release:
  stage: publish
  image: inetprocess/gitlab-release
  only:
    refs:
      - tags
  dependencies:
    - compile-debian-stretch
    - compile-debian-buster
    - compile-ubuntu-18.04
    - compile-ubuntu-19.10
    - compile-ubuntu-20.04
    - compile-fedora-31
    - compile-fedora-32
  script:
    - gitlab-release ballish_stretch_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish_buster_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish-"${CI_BUILD_TAG:-1.0.0}"-1.f31.x86_64.rpm ballish-"${CI_BUILD_TAG:-1.0.0}"-1.f32.x86_64.rpm ballish_ubuntu_18.04_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish_ubuntu_19.10_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb ballish_ubuntu_20.04_"${CI_BUILD_TAG:-1.0.0}"_amd64.deb
