#!/usr/bin/env bash

set -xe

export PATH=$(realpath ../..):$PATH

for script in tests/*.sh; do
    tmp=$(mktemp -d)
    trap "rm -rf $tmp" EXIT

    export XDG_RUNTIME_DIR="$tmp"/runtime
    export XDG_DATA_HOME="$tmp"/data

    cp -R fixtures "$tmp"
    cp -R tests "$tmp"

    echo "Running ${script}..."
    (cd "$tmp" && ./"$script" "$tmp")
done
